{{- if and .Values.certManager.enabled .Values.certManager.clusterIssuer.create }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer.name }}
  labels:
    {{- include "finaware.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.certManager.clusterIssuer.email | quote }}
    server: {{ .Values.certManager.clusterIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuer.privateKeySecretName | quote }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className | quote }}
{{- end }}
