apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finaware.fullname" . }}-secret
  labels:
    {{- include "finaware.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  OPENAI_API_KEY: {{ .Values.secret.openaiApiKey | quote }}
