apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finaware-web
  namespace: finaware
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: finaware.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finaware-web
                port:
                  number: 80
